--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/notacoderr/CrossOnlineCount-2
branches:
- master
projects:
  CrossOnlineCount-2:
    path: ""
    libs:
      - src: Falkirks/spoondetector/spoondetector
        version: ^0.0.0
      - src: jasonwynn10/libpmquery/libpmquery
        version: ^0.0.1
...
